# @package _global_
defaults:
  - override /dataset: mnist

# Extremely fast settings to verify if the code runs without errors
dataset:
  n_train: 10
  n_test: 5
evolution:
  n_pop: 2
  n_gen: 1
  n_gates: 200
engine:
  epochs: 1
strategy:
  epochs: 1
verbose: true
