# @package _global_
# High precision settings for final research results
dataset:
  n_train: 1000
  n_test: 200
evolution:
  n_pop: 20
  n_gen: 20
engine:
  epochs: 100
  lr: 0.0005
strategy:
  epochs: 10
