# Default Configuration (Consolidated)
task_name: train  #{ Options: evolution, auto_evolution, train }
model_type: standard #{ Options: standard, evolutionary_qcnn }
experiment_name: None

# Dataset parameters
dataset_name: mnist #{ Options: mnist, fashion_mnist, custom_dataset }
data_path: "./data"
n_train: 200
n_test: 50
n_val: 50
digits: [3, 6]
target_dim: 16
preprocessors: ["pca_16", "flatten"]

# Evolution parameters
n_pop: 20
n_gen: 10
n_gates: 200
mutation_rate: 0.1

# Engine parameters (Training)
engine_type: hybrid #{ Options: hybrid, qiskit }
train_epochs: 40
train_lr: 0.01
gradient_method: spsa
device: null
use_v2_primitives: true
use_scheduler: true
scheduler_patience: 5
scheduler_factor: 0.5

# Strategy parameters (Evolution Evaluation)
strategy_type: hybrid
eval_epochs: 5
eval_lr: 0.01
eval_max_iter: 50

# Feature Map parameters
feature_map_type: angle

# Global parameters
num_qubits: 16
verbose: true
seed: 42
save_dir: "./output"
output_dir: "./output"
resume_dir: null

# แจ้งเตือนเข้า Line
notifications:
  enabled: true
  title: "QCNN Training" 

# คำสั่งว่าไม่ต้องสร้างโฟลเดอร์ย่อยของ Hydra สำหรับบันทึกคำสั่งแต่ละรัน
hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  output_subdir: null
  job:
    chdir: False
  hydra_logging:
    version: 1
    root:
      level: CRITICAL
  job_logging:
    version: 1
    root:
      handlers: [console]
    handlers:
      file:
        class: logging.FileHandler
        # filename: /dev/null # For Linux/Mac
        filename: NUL # For Windows
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
