defaults:
  - config
  - _self_
task_name: train
dataset_name: fashionmnist
digits: [0, 2]
preprocessors: ["autoencoder_16"]
train_lr: 0.05
feature_map_type: angle
train_epochs: 100
scheduler_patience: 3
n_train: 1000
n_test: 200
n_val: 200

# uv run main.py --config-name fashionmnist_02_ae 'digits=[4,6]'