defaults:
  - config
  - _self_
task_name: train
dataset_name: fashionmnist
# Digits is used for folder naming and default target_labels, 
# but binary_groups will override the loading logic.
digits: [0, 2, 4, 6] 
binary_groups: [[0], [2, 4, 6]]
preprocessors: ["autoencoder_16"]
train_lr: 0.05
feature_map_type: angle
train_epochs: 100
scheduler_patience: 3
n_train: 1000
n_test: 200
n_val: 200
